'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import {
  Activity, Archive, ArrowRight, Boxes, CheckCircle2, CircleAlert, Clock3,
  Database, Download, FileArchive, FileInput, GitCompareArrows, History,
  Layers3, LoaderCircle, Network, Play, RadioTower, RefreshCw, Save,
  ShieldCheck, SlidersHorizontal, Sparkles, UserCheck, Waves, X,
} from 'lucide-react';
import { useLanguage } from '@/components/language-provider';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ApiError } from '@/services/api/client';
import { toolApi, type WorkbenchJob, type WorkbenchProject } from '@/services/api/tools';

type Source = { id: string; name: string; protocol: string; kind: string; unit: string; canonicalUnit: string; status: string; clockOffsetSeconds: number; watermarkSeconds: number; x: number; y: number; owner: string; schemaVersion: number; calibrationVersion: string; lastSeen: string | null; retentionDays: number };
type Schema = { id: string; sourceId: string; version: number; status: string; fields: Array<{ name: string; type: string; required: boolean }>; unit: string; crs: string; approvedBy: string[]; publishedAt: string | null };
type Observation = { id: string; sourceId: string; eventTime: string; ingestTime: string; rawValue: number | null; value: number | null; unit: string; quality: string; calibrationVersion: string; x: number; y: number; traceId: string; source: string };
type FusedEvent = { id: string; windowStart: string; windowEnd: string; riskScore: number; level: string; status: string; title: string; evidenceIds: string[]; modelVersionId: string; reviewer: string; reviewedAt: string | null; reviewNote?: string };
type QualityEvent = { id: string; sourceId: string; type: string; severity: string; status: string; time: string; detail: string };
type FusionWorkspace = {
  id: string; name: string; version: number; selectedSourceId: string; selectedEventId: string; windowSeconds: number; alignmentMode: string; fillPolicy: string; maxFillWindows: number;
  calibrationVersions: Array<Record<string, unknown>>; alignmentJobs: Array<Record<string, unknown>>; featureSets: Array<Record<string, unknown>>;
  fusionModels: Array<Record<string, unknown>>; modelVersions: Array<{ id: string; modelId: string; version: number; status: string; weights: Record<string, number>; thresholds: Record<string, number>; approvals: Array<{ actor: string; time: string }>; createdAt: string }>;
  fusedEvents: FusedEvent[]; qualityEvents: QualityEvent[]; approvals: Array<Record<string, unknown>>; roles: Array<{ role: string; members: string[] }>;
  audit: Array<{ id: string; time: string; action: string; actor: string; target: string; detail: string }>; lastReplay?: { from: string; to: string; observations: number; events: number; createdAt?: string }; createdAt: string; updatedAt: string;
};
type FusionAnalysis = {
  metrics: { sources: number; onlineSources: number; completeness: number; clockDriftSources: number; qualityEvents: number; fusedEvents: number; pendingReview: number; criticalEvents: number; activeModelVersion: number };
  timeAxis: string[]; alignedSeries: Array<{ sourceId: string; name: string; unit: string; values: Array<number | null>; normalized: Array<number | null> }>;
  missingMatrix: Array<{ sourceId: string; window: number; status: string }>; correlationMatrix: Array<{ left: string; right: string; value: number }>;
  topology: { nodes: Array<{ id: string; name: string; kind: string; status: string; x: number; y: number }>; edges: Array<{ source: string; target: string }> };
  spatialSignals: Array<{ sourceId: string; name: string; x: number; y: number; status: string; value: number | null; unit: string }>;
  qualityEvents: QualityEvent[]; fusedTimeline: FusedEvent[]; selectedEvent: FusedEvent;
  contributions: Array<{ sourceId: string; name: string; weight: number; normalized: number; contribution: number }>;
  qualityChecks: Array<{ label: string; passed: boolean }>; replay: { from: string | null; to: string | null; observations: number; events: number };
};
type FusionResult = {
  schema: 'skyview-fusion-console-results'; version: number; stage: string; workspace: FusionWorkspace; sources: Source[]; schemas: Schema[]; observations: Observation[]; analysis: FusionAnalysis;
  runtime: { controlPlane: string; computePlane: string; ingestion: Record<string, string>; streamProcessing: Record<string, string>; timeSeriesStore: Record<string, string>; modelWorker: Record<string, string>; supportedImports: string[]; supportedExports: string[]; arbitraryCodeExecution: boolean };
  exports: { reportMarkdown: string; observationsCsv: string; eventsCsv: string; auditCsv: string; lineageJson: string; backupJson: string; packageBase64: string };
  importSummary?: { accepted: number; rejected: number; violations: Array<{ line: number; reason: string }> };
};

const views = [
  ['topology', '源与拓扑', 'Sources & topology'], ['alignment', '对齐与质量', 'Alignment & quality'],
  ['fusion', '融合研判', 'Fusion review'], ['replay', '事件回放', 'Event replay'],
  ['delivery', '治理与交付', 'Governance & delivery'],
] as const;
const terminal = new Set(['succeeded', 'failed', 'canceled']);
const wait = (milliseconds: number) => new Promise((resolve) => window.setTimeout(resolve, milliseconds));
const percent = (value: number) => `${Math.round(value * 100)}%`;
const statusLabel: Record<string, string> = { online: '在线', degraded: '降级', registered: '已注册', published: '已发布', review: '待复核', confirmed: '已确认', rejected: '已排除', open: '未处理', closed: '已关闭', warning: '预警', high: '高风险', critical: '严重', normal: '正常', succeeded: '已完成', draft: '草稿' };

async function waitForJob(id: string): Promise<WorkbenchJob | null> {
  for (let attempt = 0; attempt < 120; attempt += 1) {
    const job = await toolApi.getJob(id);
    if (terminal.has(job.status)) return job;
    await wait(750);
  }
  return null;
}

function correlation(left: Array<number | null>, right: Array<number | null>) {
  const pairs = left.map((value, index) => [value, right[index]] as const).filter((pair): pair is readonly [number, number] => pair[0] !== null && pair[1] !== null);
  if (pairs.length < 3) return 0;
  const mx = pairs.reduce((sum, item) => sum + item[0], 0) / pairs.length; const my = pairs.reduce((sum, item) => sum + item[1], 0) / pairs.length;
  const numerator = pairs.reduce((sum, item) => sum + (item[0] - mx) * (item[1] - my), 0); const denominator = Math.sqrt(pairs.reduce((sum, item) => sum + (item[0] - mx) ** 2, 0) * pairs.reduce((sum, item) => sum + (item[1] - my) ** 2, 0));
  return denominator ? Math.round(numerator / denominator * 1000) / 1000 : 0;
}

function sampleResult(): FusionResult {
  const times = Array.from({ length: 16 }, (_, index) => `2026-09-10T${String(8 + Math.floor(index / 12)).padStart(2, '0')}:${String((index % 12) * 5).padStart(2, '0')}:00Z`);
  const specs: Array<[string, string, string, string, string, number, number, Array<number | null>]> = [
    ['src-gnss', '北坡 GNSS', 'GNSS', 'displacement', 'mm', 32, 31, [4.2, 4.4, 4.8, 5.1, 5.6, 6.3, 7.4, 8.8, 10.2, 11.9, 14.1, 17, 20.4, 24.8, 29.9, 35.6]],
    ['src-rain', '北坡雨量', 'MQTT', 'rainfall', 'mm/h', 23, 24, [0, 0, 1, 2, 5, 9, 16, 24, 38, 55, 72, 68, 51, 33, 20, 11]],
    ['src-pore', '坡脚孔压', 'HTTP', 'pore-pressure', 'kPa', 42, 64, [82, 83, 84, 85, 87, 90, 94, 99, 105, 112, 121, 130, 139, 146, 151, 154]],
    ['src-seismic', '微震事件流', 'Kafka', 'microseismic-energy', 'kJ', 58, 45, [1.2, 1, 1.4, 1.8, 1.5, 2.1, 2.4, 3.1, 4.8, 7.2, 12.6, 10.4, 18.2, 22.1, 14.8, 9.6]],
    ['src-insar', 'InSAR 形变', 'FILE', 'displacement', 'mm', 70, 33, [3.8, null, null, 4.7, null, null, 7.1, null, null, 12.8, null, null, 21.6, null, null, 33.9]],
    ['src-temp', '地表温度', 'OPC-UA', 'temperature', '°C', 77, 67, [21.4, 21.6, 22, 22.5, 23.1, 24, 25.2, 26.4, 27.6, 28.1, 27.8, 27, 26.2, 25.4, 24.9, 24.3]],
  ];
  const sources: Source[] = specs.map(([id, name, protocol, kind, unit, x, y]) => ({ id, name, protocol, kind, unit, canonicalUnit: unit, status: id === 'src-insar' ? 'degraded' : 'online', clockOffsetSeconds: id === 'src-seismic' ? 42 : id === 'src-rain' ? 3 : 0, watermarkSeconds: id === 'src-seismic' ? 90 : 30, x, y, owner: '监测数据组', schemaVersion: 2, calibrationVersion: 'cal-v2', lastSeen: times.at(-1)!, retentionDays: 365 }));
  const schemas: Schema[] = sources.map((source) => ({ id: `schema-${source.id}`, sourceId: source.id, version: 2, status: 'published', fields: [{ name: 'eventTime', type: 'datetime', required: true }, { name: 'value', type: 'number', required: true }, { name: 'quality', type: 'enum', required: true }], unit: source.unit, crs: 'LOCAL-METER', approvedBy: ['源管理员', '数据工程师'], publishedAt: '2026-09-09T09:00:00Z' }));
  const observations: Observation[] = specs.flatMap(([sourceId, , , , unit, x, y, values]) => values.map((value, index) => ({ id: `obs-${sourceId}-${String(index).padStart(2, '0')}`, sourceId, eventTime: times[index], ingestTime: times[index], rawValue: value, value, unit, quality: value === null ? 'missing' : 'good', calibrationVersion: 'cal-v2', x, y, traceId: `trace-${index}`, source: 'deterministic-benchmark' })));
  const alignedSeries = specs.map(([sourceId, name, , , unit, , , values]) => { const finite = values.filter((item): item is number => item !== null); const low = Math.min(...finite); const high = Math.max(...finite); return { sourceId, name, unit, values, normalized: values.map((value) => value === null ? null : Math.round((value - low) / Math.max(high - low, .0001) * 1000) / 1000) }; });
  const correlationMatrix = sources.flatMap((left) => sources.map((right) => ({ left: left.id, right: right.id, value: left.id === right.id ? 1 : correlation(alignedSeries.find((item) => item.sourceId === left.id)!.values, alignedSeries.find((item) => item.sourceId === right.id)!.values) })));
  const fusedEvents: FusedEvent[] = [
    { id: 'fused-001', windowStart: times[9], windowEnd: times[10], riskScore: .61, level: 'warning', status: 'confirmed', title: '降雨与孔压同步抬升', evidenceIds: ['obs-src-rain-09', 'obs-src-pore-09', 'obs-src-gnss-09'], modelVersionId: 'model-v3', reviewer: '张审核员', reviewedAt: times[11] },
    { id: 'fused-002', windowStart: times[12], windowEnd: times[13], riskScore: .79, level: 'high', status: 'confirmed', title: '位移加速伴随微震增强', evidenceIds: ['obs-src-gnss-12', 'obs-src-seismic-12', 'obs-src-insar-12'], modelVersionId: 'model-v3', reviewer: '李审核员', reviewedAt: times[14] },
    { id: 'fused-003', windowStart: times[15], windowEnd: '2026-09-10T09:20:00Z', riskScore: .88, level: 'critical', status: 'review', title: '多源形变证据持续增强', evidenceIds: ['obs-src-gnss-15', 'obs-src-pore-15', 'obs-src-seismic-15', 'obs-src-insar-15'], modelVersionId: 'model-v3', reviewer: '', reviewedAt: null },
  ];
  const qualityEvents: QualityEvent[] = [{ id: 'quality-001', sourceId: 'src-insar', type: 'missing', severity: 'warning', status: 'open', time: times[14], detail: '稀疏重访源存在预期空窗，已限制前向填充窗口' }, { id: 'quality-002', sourceId: 'src-seismic', type: 'clock-drift', severity: 'warning', status: 'open', time: times[15], detail: '事件时钟较接入时钟偏移 42 秒' }, { id: 'quality-003', sourceId: 'src-rain', type: 'spike', severity: 'info', status: 'closed', time: times[10], detail: '强降雨突增经复核后保留' }];
  const weights = { 'src-gnss': .28, 'src-rain': .17, 'src-pore': .22, 'src-seismic': .18, 'src-insar': .12, 'src-temp': .03 };
  const workspace: FusionWorkspace = { id: 'fusion-north-slope', name: '北岭边坡多源联合研判', version: 4, selectedSourceId: 'src-gnss', selectedEventId: 'fused-003', windowSeconds: 300, alignmentMode: 'event-time', fillPolicy: 'forward-limited', maxFillWindows: 2, calibrationVersions: [{ id: 'cal-v2', status: 'published', factor: 1, offset: 0, approvedBy: ['源管理员', '业务审核'] }], alignmentJobs: [{ id: 'align-20260910', status: 'succeeded', windowSeconds: 300, inputRows: observations.length, outputWindows: 16, lateRows: 1 }], featureSets: [{ id: 'features-v3', name: '边坡联合特征', version: 3, status: 'published', features: ['位移速率', '累计雨量', '孔压增量', '微震能量', 'InSAR 一致性'], lineage: sources.map((item) => item.id) }], fusionModels: [{ id: 'model-slope-risk', name: '边坡多源证据融合', type: 'weighted-evidence', activeVersionId: 'model-v3', owner: '模型组' }], modelVersions: [{ id: 'model-v3', modelId: 'model-slope-risk', version: 3, status: 'published', weights, thresholds: { warning: .55, high: .72, critical: .86 }, approvals: [{ actor: '模型作者', time: times[0] }, { actor: '业务审核', time: times[1] }], createdAt: times[0] }], fusedEvents, qualityEvents, approvals: [{ id: 'approval-model-v3', target: 'model-v3', status: 'approved', actors: ['模型作者', '业务审核'] }], roles: [{ role: '源管理员', members: ['王源管'] }, { role: '数据工程师', members: ['赵工程师'] }, { role: '模型作者', members: ['陈模型'] }, { role: '业务审核', members: ['李审核员'] }], audit: [{ id: 'audit-seed', time: times[14], action: 'review-fused-event', actor: '李审核员', target: 'fused-002', detail: '复核位移与微震联合证据并确认高风险事件' }], createdAt: times[0], updatedAt: times[15] };
  const contributions = sources.map((source) => { const normalized = alignedSeries.find((item) => item.sourceId === source.id)!.normalized.findLast((item) => item !== null) ?? 0; return { sourceId: source.id, name: source.name, weight: weights[source.id as keyof typeof weights], normalized, contribution: Math.round(normalized * weights[source.id as keyof typeof weights] * 10000) / 10000 }; }).sort((a, b) => b.contribution - a.contribution);
  const qualityChecks = ['数据源均绑定已发布 schema', '单位已映射到规范单位', '观测保留事件时间与接入时间', '融合结论可追溯原始观测', '已发布模型完成双人审批', '校准版本进入观测血缘'].map((label) => ({ label, passed: true }));
  return { schema: 'skyview-fusion-console-results', version: 2, stage: 'load-sample', workspace, sources, schemas, observations, analysis: { metrics: { sources: 6, onlineSources: 5, completeness: 92.7, clockDriftSources: 1, qualityEvents: 2, fusedEvents: 3, pendingReview: 1, criticalEvents: 1, activeModelVersion: 3 }, timeAxis: times, alignedSeries, missingMatrix: sources.flatMap((source) => times.map((_, window) => ({ sourceId: source.id, window, status: alignedSeries.find((item) => item.sourceId === source.id)!.values[window] === null ? 'missing' : 'good' }))), correlationMatrix, topology: { nodes: [...sources.map((item) => ({ id: item.id, name: item.name, kind: 'source', status: item.status, x: item.x, y: item.y })), { id: 'aligner', name: '事件时间对齐', kind: 'process', status: 'healthy', x: 50, y: 32 }, { id: 'fusion', name: '融合模型 v3', kind: 'model', status: 'published', x: 50, y: 57 }, { id: 'decision', name: '研判事件', kind: 'output', status: 'review', x: 50, y: 82 }], edges: [...sources.map((item) => ({ source: item.id, target: 'aligner' })), { source: 'aligner', target: 'fusion' }, { source: 'fusion', target: 'decision' }] }, spatialSignals: sources.map((source) => ({ sourceId: source.id, name: source.name, x: source.x, y: source.y, status: source.status, value: alignedSeries.find((item) => item.sourceId === source.id)!.values.findLast((item) => item !== null) ?? null, unit: source.unit })), qualityEvents, fusedTimeline: fusedEvents, selectedEvent: fusedEvents[2], contributions, qualityChecks, replay: { from: times[8], to: times[15], observations: 92, events: 3 } }, runtime: { controlPlane: 'Go 项目、版本、作业、权限与审计', computePlane: 'Python 事件时间对齐、质量计算、特征与融合解释', ingestion: { mqtt: 'adapter-ready', http: 'adapter-ready', file: 'enabled', kafka: 'not-configured', opcUa: 'not-configured' }, streamProcessing: { engine: 'Kafka/Flink adapter', status: 'not-configured' }, timeSeriesStore: { engine: 'TimescaleDB/InfluxDB adapter', status: 'not-configured' }, modelWorker: { engine: 'HTTP model worker', status: 'not-configured', localDeterministicFusion: 'enabled' }, supportedImports: ['CSV', 'JSON', 'NDJSON'], supportedExports: ['CSV', 'JSON', 'Markdown', 'ZIP'], arbitraryCodeExecution: false }, exports: { reportMarkdown: '# 多源监测融合研判报告', observationsCsv: '观测ID,源ID,事件时间,数值\n', eventsCsv: '事件ID,等级,风险分,状态\n', auditCsv: '审计ID,动作,操作人\n', lineageJson: '{}', backupJson: '{}', packageBase64: '' } };
}

function downloadText(content: string, fileName: string, type = 'text/plain;charset=utf-8') { const url = URL.createObjectURL(new Blob(['\ufeff', content], { type })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = fileName; document.body.appendChild(anchor); anchor.click(); anchor.remove(); URL.revokeObjectURL(url); }
function downloadBase64(content: string, fileName: string) { const bytes = Uint8Array.from(atob(content), (character) => character.charCodeAt(0)); const url = URL.createObjectURL(new Blob([bytes], { type: 'application/zip' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = fileName; document.body.appendChild(anchor); anchor.click(); anchor.remove(); URL.revokeObjectURL(url); }

function TopologyMap({ result }: { result: FusionResult }) {
  const nodes = result.analysis.topology.nodes; const nodeMap = new globalThis.Map(nodes.map((item) => [item.id, item]));
  return <svg className="fusionx-topology" viewBox="0 0 760 380" role="img" aria-label="数据源、时间对齐、融合模型和研判事件拓扑">
    <defs><pattern id="fusion-grid" width="30" height="30" patternUnits="userSpaceOnUse"><path d="M30 0H0V30"/></pattern><marker id="fusion-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8Z"/></marker></defs><rect width="760" height="380" className="base"/><rect width="760" height="380" fill="url(#fusion-grid)"/>
    {result.analysis.topology.edges.map((edge) => { const left = nodeMap.get(edge.source); const right = nodeMap.get(edge.target); return left && right ? <line key={`${edge.source}-${edge.target}`} x1={left.x * 7.6} y1={left.y * 3.8} x2={right.x * 7.6} y2={right.y * 3.8} markerEnd="url(#fusion-arrow)"/> : null; })}
    {nodes.map((node) => <g key={node.id} className={`node ${node.kind} ${node.status}`} transform={`translate(${node.x * 7.6} ${node.y * 3.8})`}><circle r={node.kind === 'source' ? 20 : 26}/><text y={node.kind === 'source' ? 35 : 43}>{node.name}</text><small/></g>)}
  </svg>;
}

function TimeAlignmentChart({ result }: { result: FusionResult }) {
  const colors = ['#0a8796', '#d77a16', '#3158a7', '#9b3f68', '#6f5aa7', '#30805f'];
  return <svg className="fusionx-series-chart" viewBox="0 0 920 330" role="img" aria-label="多源监测统一时间轴">
    <rect width="920" height="330" className="base"/>{[0, 1, 2, 3, 4].map((line) => <line key={line} x1="54" y1={38 + line * 58} x2="890" y2={38 + line * 58}/>)}
    {result.analysis.alignedSeries.map((series, seriesIndex) => { const points = series.normalized.map((value, index) => value === null ? null : `${54 + index * 55.5},${280 - value * 232}`); const chunks: string[][] = []; let current: string[] = []; points.forEach((point) => { if (point) current.push(point); else if (current.length) { chunks.push(current); current = []; } }); if (current.length) chunks.push(current); return <g key={series.sourceId} style={{ '--series-color': colors[seriesIndex] } as React.CSSProperties}>{chunks.map((chunk, index) => <polyline key={index} points={chunk.join(' ')}/>)}{points.map((point, index) => point ? <circle key={index} cx={Number(point.split(',')[0])} cy={Number(point.split(',')[1])} r="3"/> : null)}</g>; })}
    {result.analysis.timeAxis.filter((_, index) => index % 3 === 0).map((time, index) => <text key={time} x={54 + index * 166.5} y="314">{time.slice(11, 16)}</text>)}
  </svg>;
}

function SpatialMap({ result, selectedSourceId, onSelect }: { result: FusionResult; selectedSourceId: string; onSelect: (id: string) => void }) {
  return <svg className="fusionx-spatial" viewBox="0 0 640 400" role="img" aria-label="监测源空间分布与最新信号">
    <defs><pattern id="terrain-grid" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M40 0H0V40"/></pattern><radialGradient id="risk-halo"><stop offset="0" stopColor="#d84b38" stopOpacity=".55"/><stop offset="1" stopColor="#d84b38" stopOpacity="0"/></radialGradient></defs><rect width="640" height="400" className="base"/><rect width="640" height="400" fill="url(#terrain-grid)"/><path className="terrain" d="M15 320C110 270 130 138 224 172S330 316 418 210 515 70 625 126"/><circle cx="320" cy="210" r="130" fill="url(#risk-halo)"/>
    {result.analysis.spatialSignals.map((item) => <g key={item.sourceId} role="button" tabIndex={0} className={item.sourceId === selectedSourceId ? 'active' : ''} onClick={() => onSelect(item.sourceId)} transform={`translate(${item.x * 6.4} ${item.y * 4})`}><circle r={item.sourceId === selectedSourceId ? 15 : 11}/><text y="-20">{item.name}</text><text y="30">{item.value ?? '—'} {item.unit}</text></g>)}
  </svg>;
}

export function FusionConsoleWorkbench({ executionAllowed = true }: { executionAllowed?: boolean }) {
  const { text } = useLanguage(); const [view, setView] = useState<(typeof views)[number][0]>('topology'); const [result, setResult] = useState<FusionResult>(() => sampleResult());
  const [projects, setProjects] = useState<WorkbenchProject[]>([]); const [projectId, setProjectId] = useState(''); const [projectTitle, setProjectTitle] = useState('北岭边坡多源联合研判'); const [actor, setActor] = useState('当前数据工程师');
  const [selectedSourceId, setSelectedSourceId] = useState('src-gnss'); const [selectedEventId, setSelectedEventId] = useState('fused-003'); const [windowSeconds, setWindowSeconds] = useState(300); const [factor, setFactor] = useState(1); const [offset, setOffset] = useState(0);
  const [replayFrom, setReplayFrom] = useState('2026-09-10T08:40:00Z'); const [replayTo, setReplayTo] = useState('2026-09-10T09:15:00Z'); const [running, setRunning] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const importInput = useRef<HTMLInputElement>(null);

  useEffect(() => { let active = true; toolApi.listProjects('fusion-console').then((items) => { if (!active) return; setProjects(items); const project = items[0]; const saved = project?.state.fusionConsole as { result?: FusionResult } | undefined; if (project && saved?.result?.schema === 'skyview-fusion-console-results') { setProjectId(project.id); setProjectTitle(project.title); setResult(saved.result); setSelectedSourceId(saved.result.workspace.selectedSourceId); setSelectedEventId(saved.result.workspace.selectedEventId); } }).catch(() => undefined); return () => { active = false; }; }, []);
  const projectState = (next = result) => ({ fusionConsole: { result: next } });
  const ensureProject = async () => { const existing = projects.find((item) => item.id === projectId); if (existing) return existing; const created = await toolApi.createProject('fusion-console', projectTitle, projectState()); setProjects((items) => [created, ...items]); setProjectId(created.id); return created; };
  const storeResult = async (project: WorkbenchProject, output: FusionResult) => { setResult(output); const saved = await toolApi.updateProject(project.id, projectTitle, projectState(output)); setProjects((items) => [saved, ...items.filter((item) => item.id !== saved.id)]); };
  const execute = async (action: string, extra: Record<string, unknown> = {}) => { if (!executionAllowed) { setError(text('多源融合服务当前不可用', 'Fusion service is unavailable')); return null; } setRunning(true); setError(''); setMessage(text('Go 已登记作业，Python 正在重算时间对齐、质量和融合证据…', 'The job is registered; alignment, quality, and evidence are updating…')); try { const project = await ensureProject(); const created = await toolApi.createJob(project.id, 'fusion-console', action, { state: result, actor, ...extra }, crypto.randomUUID()); const job = await waitForJob(created.job.id); if (!job) throw new Error(text('作业仍在后台运行。', 'The job is still running.')); if (job.status === 'failed') throw new Error(job.error || text('融合计算失败。', 'Fusion calculation failed.')); if (job.status === 'canceled') throw new Error(text('作业已取消。', 'The job was canceled.')); const output = job.result as FusionResult; if (output.schema !== 'skyview-fusion-console-results') throw new Error(text('服务端结果不兼容。', 'The service result is incompatible.')); await storeResult(project, output); setSelectedEventId(output.workspace.selectedEventId); setMessage(text('统一时间轴、质量记录、融合结论和审计已更新。', 'Timeline, quality, conclusions, and audit were updated.')); return output; } catch (caught) { setError(caught instanceof ApiError || caught instanceof Error ? caught.message : text('操作失败。', 'Operation failed.')); setMessage(''); return null; } finally { setRunning(false); } };
  const saveProject = async () => { setSaving(true); setError(''); try { const existing = projects.find((item) => item.id === projectId); const saved = existing ? await toolApi.updateProject(existing.id, projectTitle, projectState()) : await toolApi.createProject('fusion-console', projectTitle, projectState()); setProjects((items) => [saved, ...items.filter((item) => item.id !== saved.id)]); setProjectId(saved.id); setMessage(text('融合项目已保存。', 'Fusion project saved.')); } catch (caught) { setError(caught instanceof Error ? caught.message : text('保存失败。', 'Save failed.')); } finally { setSaving(false); } };
  const createVersion = async () => { try { const project = await ensureProject(); await toolApi.createVersion(project.id, `融合研判 v${result.workspace.version} · ${new Date().toLocaleString('zh-CN')}`, projectState()); setMessage(text('已创建不可变版本。', 'Immutable version created.')); } catch (caught) { setError(caught instanceof Error ? caught.message : text('版本创建失败。', 'Version creation failed.')); } };
  const importObservations = async (file?: File) => { if (!file) return; if (file.size > 4_000_000) { setError(text('观测文件不能超过 4 MB。', 'Observation file must not exceed 4 MB.')); return; } await execute('import-observations', { fileName: file.name, content: await file.text() }); if (importInput.current) importInput.current.value = ''; };
  const selectProject = (id: string) => { setProjectId(id); const project = projects.find((item) => item.id === id); if (!project) { setResult(sampleResult()); setProjectTitle('北岭边坡多源联合研判'); return; } const saved = project.state.fusionConsole as { result?: FusionResult } | undefined; if (saved?.result?.schema === 'skyview-fusion-console-results') { setResult(saved.result); setProjectTitle(project.title); } };

  const source = result.sources.find((item) => item.id === selectedSourceId) ?? result.sources[0]; const schema = result.schemas.find((item) => item.sourceId === source.id)!; const event = result.workspace.fusedEvents.find((item) => item.id === selectedEventId) ?? result.analysis.selectedEvent; const evidence = result.observations.filter((item) => event.evidenceIds.includes(item.id)); const sourceIndex = new globalThis.Map(result.sources.map((item, index) => [item.id, index])); const modelVersion = result.workspace.modelVersions[0];
  const maxContribution = Math.max(.01, ...result.analysis.contributions.map((item) => item.contribution)); const qualityBySource = useMemo(() => new globalThis.Map(result.analysis.qualityEvents.map((item) => [item.sourceId, item])), [result.analysis.qualityEvents]);

  return <div className="fusionx-workbench">
    <header className="fusionx-commandbar"><div className="fusionx-project"><Network/><NativeSelect aria-label={text('选择融合项目', 'Select fusion project')} value={projectId} onChange={(event) => selectProject(event.target.value)}><NativeSelectOption value="">{text('当前本地项目', 'Current local project')}</NativeSelectOption>{projects.map((project) => <NativeSelectOption key={project.id} value={project.id}>{project.title}</NativeSelectOption>)}</NativeSelect><Input aria-label={text('项目名称', 'Project name')} value={projectTitle} onChange={(event) => setProjectTitle(event.target.value)}/><span>{text('事件时间基准', 'Event-time baseline')}</span></div><div className="fusionx-actions"><input ref={importInput} hidden type="file" accept=".csv,.json,.ndjson,text/csv,application/json" onChange={(event) => void importObservations(event.target.files?.[0])}/><Button size="sm" variant="outline" onClick={() => importInput.current?.click()}><FileInput/>{text('导入观测', 'Import')}</Button><Button size="sm" variant="outline" disabled={saving} onClick={() => void saveProject()}>{saving ? <LoaderCircle className="spin"/> : <Save/>}{text('保存', 'Save')}</Button><Button size="sm" variant="outline" onClick={() => void createVersion()}><Archive/>{text('版本', 'Version')}</Button><Button size="sm" disabled={running} onClick={() => void execute('run-fusion')}>{running ? <LoaderCircle className="spin"/> : <Sparkles/>}{text('执行融合', 'Run fusion')}</Button></div></header>
    <section className="fusionx-kpis"><article><RadioTower/><span>{text('在线数据源', 'Online sources')}</span><strong>{result.analysis.metrics.onlineSources}<small>/{result.analysis.metrics.sources}</small></strong><em>{result.analysis.metrics.completeness}% {text('完整率', 'complete')}</em></article><article><Clock3/><span>{text('统一时间窗', 'Time window')}</span><strong>{result.workspace.windowSeconds}<small>s</small></strong><em>{result.workspace.alignmentMode}</em></article><article className="quality"><CircleAlert/><span>{text('质量事件', 'Quality events')}</span><strong>{result.analysis.metrics.qualityEvents}</strong><em>{result.analysis.metrics.clockDriftSources} {text('源时钟漂移', 'clock drift')}</em></article><article className="risk"><Waves/><span>{text('融合事件', 'Fused events')}</span><strong>{result.analysis.metrics.fusedEvents}</strong><em>{result.analysis.metrics.pendingReview} {text('条待复核', 'pending')}</em></article><article><Layers3/><span>{text('活跃模型', 'Active model')}</span><strong>v{result.analysis.metrics.activeModelVersion}</strong><em>{statusLabel[modelVersion.status]}</em></article><article><ShieldCheck/><span>{text('治理门禁', 'Governance gates')}</span><strong>{result.analysis.qualityChecks.filter((item) => item.passed).length}<small>/{result.analysis.qualityChecks.length}</small></strong><em>{text('血缘可追溯', 'traceable')}</em></article></section>
    <Tabs value={view} onValueChange={(value) => setView(value as typeof view)} className="fusionx-tabs-shell"><TabsList className="fusionx-tabs" variant="line">{views.map(([id, zh, en], index) => <TabsTrigger key={id} value={id}><b>{String(index + 1).padStart(2, '0')}</b>{text(zh, en)}</TabsTrigger>)}</TabsList></Tabs>
    {(message || error) && <div className={`fusionx-status ${error ? 'error' : ''}`}>{error ? <CircleAlert/> : <CheckCircle2/>}<span>{error || message}</span><button aria-label={text('关闭状态', 'Dismiss')} onClick={() => { setMessage(''); setError(''); }}><X/></button></div>}
    <main className="fusionx-stage">
      {view === 'topology' && <div className="fusionx-view fusionx-topology-view">
        <aside className="fusionx-surface fusionx-source-list"><header><RadioTower/><div><span>{text('数据源注册表', 'Source registry')}</span><strong>{result.sources.length} {text('个来源', 'sources')}</strong></div></header>{result.sources.map((item) => <button key={item.id} className={item.id === source.id ? 'active' : ''} onClick={() => setSelectedSourceId(item.id)}><i className={item.status}/><span><strong>{item.name}</strong><small>{item.protocol} · {item.kind}</small></span><b>{statusLabel[item.status]}</b></button>)}</aside>
        <section className="fusionx-surface fusionx-topology-card"><header><Network/><div><span>{text('流转拓扑', 'Flow topology')}</span><strong>{text('数据源 → 事件时间 → 模型 → 研判', 'Sources → event time → model → decision')}</strong></div><em>{text('全链路追踪', 'End-to-end lineage')}</em></header><TopologyMap result={result}/><footer>{result.sources.map((item) => <span key={item.id}><i className={item.status}/>{item.name}<b>{item.clockOffsetSeconds}s</b></span>)}</footer></section>
        <aside className="fusionx-surface fusionx-source-detail"><header><Database/><div><span>{text('源详情', 'Source details')}</span><strong>{source.name}</strong></div><em>{statusLabel[source.status]}</em></header><div className="fusionx-facts"><p><span>{text('协议', 'Protocol')}</span><strong>{source.protocol}</strong></p><p><span>{text('指标单位', 'Unit')}</span><strong>{source.canonicalUnit}</strong></p><p><span>Schema</span><strong>v{source.schemaVersion}</strong></p><p><span>{text('校准版本', 'Calibration')}</span><strong>{source.calibrationVersion}</strong></p><p><span>{text('时钟偏移', 'Clock offset')}</span><strong>{source.clockOffsetSeconds}s</strong></p><p><span>{text('水位线', 'Watermark')}</span><strong>{source.watermarkSeconds}s</strong></p></div><section className="fusionx-health"><span>{text('源状态', 'Source health')}</span><strong>{qualityBySource.has(source.id) ? text('需要处理', 'Action needed') : text('运行稳定', 'Stable')}</strong><small>{qualityBySource.get(source.id)?.detail ?? text('未发现开放质量事件', 'No open quality issue')}</small></section><Button variant="outline" onClick={() => { setView('alignment'); }}><Activity/>{text('查看时间轴', 'Open timeline')}</Button></aside>
      </div>}

      {view === 'alignment' && <div className="fusionx-view fusionx-alignment-view">
        <section className="fusionx-surface fusionx-series"><header><Activity/><div><span>{text('统一事件时间轴', 'Unified event timeline')}</span><strong>{result.workspace.windowSeconds}s {text('窗口 · 原始量纲独立显示', 'window · independent scales')}</strong></div><div className="fusionx-inline-controls"><Input aria-label={text('窗口秒数', 'Window seconds')} type="number" value={windowSeconds} onChange={(event) => setWindowSeconds(Number(event.target.value))}/><Button size="sm" onClick={() => void execute('align-observations', { windowSeconds })} disabled={running}><RefreshCw/>{text('重新对齐', 'Realign')}</Button></div></header><TimeAlignmentChart result={result}/><footer>{result.analysis.alignedSeries.map((item, index) => <span key={item.sourceId}><i style={{ '--legend': ['#0a8796', '#d77a16', '#3158a7', '#9b3f68', '#6f5aa7', '#30805f'][index] } as React.CSSProperties}/>{item.name}<b>{item.unit}</b></span>)}</footer></section>
        <aside className="fusionx-surface fusionx-missing"><header><Boxes/><div><span>{text('缺失热力图', 'Missingness heatmap')}</span><strong>{text('源 × 时间窗', 'Source × window')}</strong></div></header><div>{result.sources.map((item) => <section key={item.id}><span>{item.name}</span><p>{result.analysis.missingMatrix.filter((cell) => cell.sourceId === item.id).map((cell) => <i key={cell.window} className={cell.status} title={`${item.name} · ${result.analysis.timeAxis[cell.window]?.slice(11, 16)}`}/>)}</p></section>)}</div><footer><span><i className="good"/>{text('有效', 'Valid')}</span><span><i className="missing"/>{text('缺失', 'Missing')}</span></footer></aside>
        <aside className="fusionx-surface fusionx-correlation"><header><GitCompareArrows/><div><span>{text('相关矩阵', 'Correlation matrix')}</span><strong>{text('窗口内 Pearson', 'Window Pearson')}</strong></div></header><div className="fusionx-matrix" style={{ '--matrix-size': result.sources.length } as React.CSSProperties}>{result.sources.map((item) => <b key={`h-${item.id}`}>{item.name.replace('北坡 ', '').slice(0, 4)}</b>)}{result.sources.flatMap((left) => result.sources.map((right) => { const value = result.analysis.correlationMatrix.find((item) => item.left === left.id && item.right === right.id)?.value ?? 0; return <i key={`${left.id}-${right.id}`} style={{ '--corr': Math.abs(value) } as React.CSSProperties} title={`${left.name} × ${right.name}: ${value}`}>{value.toFixed(2)}</i>; }))}</div></aside>
        <aside className="fusionx-surface fusionx-quality-list"><header><CircleAlert/><div><span>{text('质量事件', 'Quality events')}</span><strong>{result.analysis.qualityEvents.length} {text('条记录', 'records')}</strong></div></header>{result.analysis.qualityEvents.map((item) => <article key={item.id} className={item.severity}><i/><span><strong>{result.sources.find((sourceItem) => sourceItem.id === item.sourceId)?.name}</strong><small>{item.detail}</small></span><em>{statusLabel[item.status]}</em></article>)}<Button variant="outline" onClick={() => void execute('run-quality-checks')} disabled={running}><ShieldCheck/>{text('重新检查', 'Run checks')}</Button></aside>
      </div>}

      {view === 'fusion' && <div className="fusionx-view fusionx-fusion-view">
        <section className="fusionx-surface fusionx-spatial-card"><header><Network/><div><span>{text('空间信号场', 'Spatial signal field')}</span><strong>{text('点击站点查看来源', 'Select a source')}</strong></div><em>{text('本地坐标', 'Local coordinates')}</em></header><SpatialMap result={result} selectedSourceId={source.id} onSelect={setSelectedSourceId}/></section>
        <section className="fusionx-surface fusionx-contribution"><header><Sparkles/><div><span>{text('融合解释', 'Fusion explanation')}</span><strong>{event.title}</strong></div><em className={event.level}>{percent(event.riskScore)}</em></header><div>{result.analysis.contributions.map((item) => <article key={item.sourceId}><span><strong>{item.name}</strong><small>{text('权重', 'weight')} {percent(item.weight)} · {text('归一化', 'normalized')} {percent(item.normalized)}</small></span><p><i style={{ width: `${item.contribution / maxContribution * 100}%` }}/></p><b>{item.contribution.toFixed(3)}</b></article>)}</div><footer><span>{text('模型版本', 'Model version')} <b>{event.modelVersionId}</b></span><span>{text('证据', 'Evidence')} <b>{event.evidenceIds.length}</b></span><span>{text('状态', 'Status')} <b>{statusLabel[event.status]}</b></span></footer></section>
        <aside className="fusionx-surface fusionx-event-queue"><header><Waves/><div><span>{text('融合事件队列', 'Fused event queue')}</span><strong>{result.workspace.fusedEvents.length} {text('条', 'events')}</strong></div></header>{result.workspace.fusedEvents.map((item) => <button key={item.id} className={`${item.id === event.id ? 'active' : ''} ${item.level}`} onClick={() => setSelectedEventId(item.id)}><em>{percent(item.riskScore)}</em><span><strong>{item.title}</strong><small>{item.windowStart.slice(11, 16)} · {item.evidenceIds.length} {text('条证据', 'evidence')}</small></span><b>{statusLabel[item.status]}</b></button>)}<section><Button variant="outline" disabled={running} onClick={() => void execute('review-fused-event', { eventId: event.id, decision: 'rejected', note: '人工复核后排除' })}>{text('排除', 'Reject')}</Button><Button disabled={running} onClick={() => void execute('review-fused-event', { eventId: event.id, decision: 'confirmed', note: '人工确认多源证据一致' })}><UserCheck/>{text('确认事件', 'Confirm')}</Button></section></aside>
      </div>}

      {view === 'replay' && <div className="fusionx-view fusionx-replay-view">
        <section className="fusionx-surface fusionx-replay-timeline"><header><History/><div><span>{text('事件回放', 'Event replay')}</span><strong>{text('原始观测 → 特征 → 模型 → 结论', 'Observation → feature → model → conclusion')}</strong></div><div className="fusionx-replay-controls"><Input aria-label={text('回放开始时间', 'Replay start')} value={replayFrom} onChange={(eventInput) => setReplayFrom(eventInput.target.value)}/><ArrowRight/><Input aria-label={text('回放结束时间', 'Replay end')} value={replayTo} onChange={(eventInput) => setReplayTo(eventInput.target.value)}/><Button size="sm" disabled={running} onClick={() => void execute('replay-window', { from: replayFrom, to: replayTo })}><Play/>{text('回放', 'Replay')}</Button></div></header><div className="fusionx-event-track">{result.analysis.fusedTimeline.map((item, index) => <button key={item.id} className={`${item.level} ${item.id === event.id ? 'active' : ''}`} style={{ left: `${12 + index * 35}%` }} onClick={() => setSelectedEventId(item.id)}><i/><strong>{item.windowStart.slice(11, 16)}</strong><span>{item.title}</span><em>{percent(item.riskScore)}</em></button>)}</div><footer><span>{text('回放范围', 'Range')} <b>{result.analysis.replay.from?.slice(11, 16)}–{result.analysis.replay.to?.slice(11, 16)}</b></span><span>{text('观测', 'Observations')} <b>{result.analysis.replay.observations}</b></span><span>{text('事件', 'Events')} <b>{result.analysis.replay.events}</b></span></footer></section>
        <section className="fusionx-surface fusionx-lineage"><header><Database/><div><span>{text('证据血缘', 'Evidence lineage')}</span><strong>{event.id} · {event.modelVersionId}</strong></div></header><div className="fusionx-lineage-flow"><article><span>{text('原始观测', 'Raw observations')}</span><strong>{event.evidenceIds.length}</strong></article><ArrowRight/><article><span>{text('特征集', 'Feature set')}</span><strong>features-v3</strong></article><ArrowRight/><article><span>{text('模型版本', 'Model version')}</span><strong>{event.modelVersionId}</strong></article><ArrowRight/><article className={event.level}><span>{text('研判结论', 'Decision')}</span><strong>{percent(event.riskScore)}</strong></article></div><div className="fusionx-evidence-table"><header><span>{text('来源', 'Source')}</span><span>{text('事件时间', 'Event time')}</span><span>{text('数值', 'Value')}</span><span>{text('校准', 'Calibration')}</span><span>Trace</span></header>{evidence.map((item) => <article key={item.id}><strong>{result.sources.find((sourceItem) => sourceItem.id === item.sourceId)?.name}</strong><span>{item.eventTime.slice(11, 19)}</span><span>{item.value} {item.unit}</span><span>{item.calibrationVersion}</span><code>{item.traceId}</code></article>)}</div></section>
      </div>}

      {view === 'delivery' && <div className="fusionx-view fusionx-delivery-view">
        <aside className="fusionx-surface fusionx-governance"><header><SlidersHorizontal/><div><span>{text('源治理与校准', 'Source governance')}</span><strong>{source.name}</strong></div></header><label><span>{text('规范单位', 'Canonical unit')}</span><Input value={schema.unit} readOnly/></label><label><span>{text('坐标参考', 'CRS')}</span><Input value={schema.crs} readOnly/></label><div className="fusionx-calibration"><label><span>{text('比例系数', 'Factor')}</span><Input type="number" value={factor} onChange={(e) => setFactor(Number(e.target.value))}/></label><label><span>{text('零点偏移', 'Offset')}</span><Input type="number" value={offset} onChange={(e) => setOffset(Number(e.target.value))}/></label></div><Button variant="outline" disabled={running} onClick={() => void execute('calibrate-source', { sourceId: source.id, factor, offset })}><RefreshCw/>{text('生成校准版本', 'Create calibration')}</Button><section>{schema.approvedBy.map((item) => <p key={item}><CheckCircle2/><span>{item}</span><b>{text('已批准', 'Approved')}</b></p>)}</section></aside>
        <section className="fusionx-surface fusionx-model-card"><header><Layers3/><div><span>{text('模型注册表', 'Model registry')}</span><strong>{String(result.workspace.fusionModels[0]?.name)}</strong></div><em>{statusLabel[modelVersion.status]}</em></header><div className="fusionx-model-facts"><p><span>{text('版本', 'Version')}</span><strong>v{modelVersion.version}</strong></p><p><span>{text('特征集', 'Feature set')}</span><strong>features-v3</strong></p><p><span>{text('预警阈值', 'Warning')}</span><strong>{percent(modelVersion.thresholds.warning)}</strong></p><p><span>{text('严重阈值', 'Critical')}</span><strong>{percent(modelVersion.thresholds.critical)}</strong></p></div><section className="fusionx-approvals">{modelVersion.approvals.map((approval) => <article key={approval.actor}><UserCheck/><span><strong>{approval.actor}</strong><small>{approval.time.slice(0, 16).replace('T', ' ')}</small></span><em>{text('已签署', 'Signed')}</em></article>)}</section><Button variant="outline" disabled={running} onClick={() => void execute('publish-model-version', { versionId: modelVersion.id })}><ShieldCheck/>{text('审批并发布', 'Approve & publish')}</Button></section>
        <section className="fusionx-surface fusionx-gates"><header><ShieldCheck/><div><span>{text('交付门禁', 'Delivery gates')}</span><strong>{result.analysis.qualityChecks.filter((item) => item.passed).length}/{result.analysis.qualityChecks.length}</strong></div></header>{result.analysis.qualityChecks.map((item) => <p key={item.label} className={item.passed ? 'pass' : 'fail'}>{item.passed ? <CheckCircle2/> : <CircleAlert/>}<span>{item.label}</span><b>{item.passed ? text('通过', 'Pass') : text('阻断', 'Blocked')}</b></p>)}<Button variant="outline" disabled={running} onClick={() => void execute('validate')}><ShieldCheck/>{text('重新验证', 'Validate')}</Button></section>
        <aside className="fusionx-surface fusionx-runtime"><header><Activity/><div><span>{text('运行时接入', 'Runtime adapters')}</span><strong>{text('能力边界', 'Capability boundary')}</strong></div></header>{[['MQTT / HTTP / 文件', 'adapter-ready'], ['Kafka / Flink', result.runtime.streamProcessing.status], ['时序数据库', result.runtime.timeSeriesStore.status], ['外部模型 Worker', result.runtime.modelWorker.status]].map(([name, status]) => <article key={name}><i className={status}/><span><strong>{name}</strong><small>{status === 'not-configured' ? text('尚未配置外部服务', 'External service not configured') : text('适配器可用', 'Adapter ready')}</small></span><em>{status}</em></article>)}<small>{text('未配置的外部运行时不会伪装为已执行；当前确定性融合由 Python 计算。', 'Unconfigured runtimes are never reported as executed; deterministic fusion runs in Python.')}</small></aside>
        <section className="fusionx-surface fusionx-deliverables"><header><FileArchive/><div><span>{text('成果交付', 'Deliverables')}</span><strong>{text('报告、数据、血缘与完整包', 'Report, data, lineage, package')}</strong></div></header><div><button onClick={() => downloadText(result.exports.reportMarkdown, 'fusion-report.md')}><Download/><span><strong>{text('研判报告', 'Report')}</strong><small>Markdown</small></span></button><button onClick={() => downloadText(result.exports.eventsCsv, 'fused-events.csv', 'text/csv;charset=utf-8')}><Download/><span><strong>{text('融合事件', 'Events')}</strong><small>CSV</small></span></button><button onClick={() => downloadText(result.exports.lineageJson, 'lineage.json', 'application/json;charset=utf-8')}><Download/><span><strong>{text('证据血缘', 'Lineage')}</strong><small>JSON</small></span></button><button onClick={() => result.exports.packageBase64 ? downloadBase64(result.exports.packageBase64, 'fusion-console-package.zip') : void execute('export')}><FileArchive/><span><strong>{text('完整交付包', 'Full package')}</strong><small>ZIP</small></span></button></div><footer><Button variant="outline" disabled={running} onClick={() => void execute('export')}><RefreshCw/>{text('刷新交付物', 'Refresh deliverables')}</Button><span>{result.workspace.audit.length} {text('条审计记录', 'audit records')}</span></footer></section>
      </div>}
    </main>
  </div>;
}
