'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import {
  Activity, Archive, BellRing, CheckCircle2, CircleAlert, Database, Download,
  ExternalLink, FileInput, Filter, Gauge, GitBranch, HardHat, Layers3,
  LoaderCircle, MapPinned, Network, Play, Radar, Save, Search, Send,
  ShieldAlert, ShieldCheck, Sparkles, Tags, Waves, X,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ApiError } from '@/services/api/client';
import { toolApi, type WorkbenchJob, type WorkbenchProject } from '@/services/api/tools';

type Taxon = { id: string; label: string };
type MineRecord = {
  id: string; title: string; doi: string; year: number; authors: string[]; venue: string; abstract: string; topics: string[];
  citations: number; references: number; openAccess: boolean; url: string; providers: string[]; source: string; isDemo: boolean;
  datasetMode: 'demo' | 'live' | 'imported'; verifiedAt: string; relevance: number; novelty: number; evidenceGrade: string;
  evidenceProfile: { data: boolean; code: boolean; validation: boolean };
  mine: { hazards: Taxon[]; methods: Taxon[]; data: Taxon[]; score: number; primaryHazard: string; primaryMethod: string };
  readiness: { score: number; level: string; checks: Record<string, boolean> }; riskSignal: number;
};
type MineWorkspace = {
  id: string; name: string; mode: 'mine'; namespace: 'mine-safety'; version: number;
  query: { main: string; must: string; exact: string; exclude: string; startYear: number; endYear: number; sort: string; oaOnly: boolean; providers: string[]; page: number; perPage: number; minMineScore: number };
  collections: Array<{ id: string; name: string }>;
  library: Array<{ recordId: string; collectionId: string; status: string; priority: string; tags: string[]; note: string }>;
  evidenceNotes: { use: string; limitations: string };
  monitors: Array<{ id: string; name: string; query: string; frequency: string; enabled: boolean; lastRunAt: string; lastStatus: string; baselineIds: string[]; newIds: string[]; delivery: string; nextRunAt: string | null }>;
  monitorRuns?: Array<{ id: string; status: string; startedAt: string; newIds: string[]; notificationStatus: string }>;
  transfer: { selectedIds: string[]; history: Array<{ id: string; destination: string; recordIds: string[]; status: string; createdAt: string; requiresDestinationReview: boolean }> };
  createdAt: string; updatedAt: string;
};
type MineResult = {
  schema: 'skyview-mine-safety-radar-results'; version: number; stage: string; namespace: 'mine-safety'; workspace: MineWorkspace; records: MineRecord[];
  analysis: { yearlyTrend: Array<{ year: number; count: number }>; hazards: Array<{ id: string; label: string; count: number }>; methods: Array<{ id: string; label: string; count: number }>; data: Array<{ id: string; label: string; count: number }>; hazardMethodMatrix: Array<{ hazardId: string; methodId: string; count: number }>; readinessDistribution: Array<{ label: string; count: number }>; graph: { nodes: Array<{ id: string; label: string; type: string; weight: number }>; edges: Array<{ id: string; source: string; target: string; weight: number }> }; riskSignals: Array<{ recordId: string; title: string; hazard: string; method: string; mineScore: number; readiness: number; riskSignal: number; boundary: string }>; duplicateCount: number; averageMineScore: number; averageReadiness: number; fieldEvidence: number; reproducibleEvidence: number };
  sources: Array<{ id: string; name: string; configured: boolean; enabled: boolean; status: string; rateLimit: string; lastCheckedAt: string | null; lastError: string; latencyMs?: number; records?: number }>;
  runtime: { dataSpaceIsolated: boolean; crossModeReuseRequiresTransfer: boolean; liveSearchRequiresExplicitAction: boolean; backgroundSchedulerConfigured: boolean; persistentNotificationConfigured: boolean; safetyDecisionAutomation: boolean };
  exports: { bibtex: string; ris: string; libraryCsv: string; alertsMarkdown: string; knowledgeMarkdown: string; transferJson: string; backupJson: string };
  liveSearch?: { message: string; fallbackUsed: boolean; returned: number; returnedBeforeDomainFilter?: number; minimumMineScore?: number };
};

const views = [['overview', '安全态势'], ['discover', '文献发现'], ['library', '专业证据库'], ['graph', '灾种技术图谱'], ['evidence', '工程证据'], ['alerts', '前沿监测'], ['transfer', '转化管线'], ['sources', '数据源']] as const;
const hazards = [['slope', '边坡与滑坡'], ['rockburst', '岩爆与冲击地压'], ['gas', '瓦斯与通风'], ['water', '矿井水害'], ['fire', '火灾与自燃'], ['dust', '粉尘与职业健康'], ['tailings', '尾矿库安全'], ['equipment', '设备与人员安全']] as const;
const methods = [['remote', '遥感 / InSAR / UAV'], ['geophysics', '微震与地球物理'], ['vision', '机器视觉'], ['timeseries', '时序预测'], ['fusion', '多源融合'], ['digitaltwin', '数字孪生'], ['knowledge', '知识图谱 / 大模型'], ['physics', '物理与数值模拟']] as const;
const dataTypes = [['image', '影像'], ['waveform', '波形信号'], ['displacement', '位移监测'], ['environment', '环境传感'], ['pointcloud', '点云 / 三维'], ['text', '文本与规程']] as const;
const terminal = new Set(['succeeded', 'failed', 'canceled']);
const wait = (milliseconds: number) => new Promise((resolve) => window.setTimeout(resolve, milliseconds));
const pct = (value: number) => `${Math.round(value)}%`;

async function waitForJob(id: string): Promise<WorkbenchJob | null> {
  for (let attempt = 0; attempt < 120; attempt += 1) { const job = await toolApi.getJob(id); if (terminal.has(job.status)) return job; await wait(750); }
  return null;
}

function downloadText(content: string, fileName: string, type = 'text/plain;charset=utf-8') {
  const url = URL.createObjectURL(new Blob(['\ufeff', content], { type })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = fileName; document.body.appendChild(anchor); anchor.click(); anchor.remove(); URL.revokeObjectURL(url);
}

function classify(title: string, abstract: string, topics: string[]): MineRecord['mine'] {
  const text = `${title} ${abstract} ${topics.join(' ')}`.toLowerCase();
  const rules: Record<string, string[]> = { slope: ['边坡', '滑坡', '形变'], rockburst: ['岩爆', '冲击地压', '微震', '声发射'], gas: ['瓦斯', '通风', '气体'], water: ['水害', '突水', '地下水'], fire: ['火灾', '煤火', '自燃', '热红外'], dust: ['粉尘', '职业健康'], tailings: ['尾矿', '溃坝'], equipment: ['设备', '人员', '接近检测'] };
  const methodRules: Record<string, string[]> = { remote: ['insar', 'uav', '遥感', '无人机'], geophysics: ['微震', '声发射', '地球物理'], vision: ['视觉', '目标检测', '裂缝识别'], timeseries: ['时序', '预测', 'transformer'], fusion: ['多源', '多模态', '融合'], digitaltwin: ['数字孪生'], knowledge: ['知识图谱', '大语言', '基础模型'], physics: ['物理约束', '数值模拟'] };
  const dataRules: Record<string, string[]> = { image: ['影像', '遥感', '视觉', '热红外'], waveform: ['波形', '微震', '声发射'], displacement: ['位移', 'gnss', '形变'], environment: ['降雨', '瓦斯', '通风', '环境传感'], pointcloud: ['点云', 'lidar', '三维'], text: ['规程', '文本', '问答'] };
  const find = (items: readonly (readonly [string, string])[], ruleset: Record<string, string[]>) => items.filter(([id]) => ruleset[id]?.some((term) => text.includes(term))).map(([id, label]) => ({ id, label }));
  const foundHazards = find(hazards, rules); const foundMethods = find(methods, methodRules); const foundData = find(dataTypes, dataRules); const score = Math.min(100, foundHazards.length * 23 + foundMethods.length * 13 + foundData.length * 9 + 8);
  return { hazards: foundHazards, methods: foundMethods, data: foundData, score, primaryHazard: foundHazards[0]?.label || '未分类', primaryMethod: foundMethods[0]?.label || '未识别' };
}

function makeRecord(index: number, row: [string, number, string, string[], number, boolean]): MineRecord {
  const [title, year, abstract, topics, citations, openAccess] = row; const mine = classify(title, abstract, topics);
  const checks = { realWorld: /现场|矿区|部署|复核/.test(abstract), validation: /验证|评测|复核|案例/.test(abstract), sensor: mine.data.length > 0, method: mine.methods.length > 0, reproducibility: /数据集|复现|开源/.test(abstract), uncertainty: /误差|不确定|校准/.test(abstract) };
  const readinessScore = Math.min(100, (checks.realWorld ? 20 : 0) + (checks.validation ? 20 : 0) + (checks.sensor ? 15 : 0) + (checks.method ? 15 : 0) + (checks.reproducibility ? 15 : 0) + (checks.uncertainty ? 10 : 0) + 4);
  return { id: `mine-${String(index).padStart(2, '0')}`, title, doi: `10.9000/skyview.mine.${String(index).padStart(2, '0')}`, year, authors: ['SkyViewLab 离线基准'], venue: '矿山安全离线基准数据集', abstract, topics, citations, references: Math.max(8, Math.round(citations / 2)), openAccess, url: `https://doi.org/10.9000/skyview.mine.${String(index).padStart(2, '0')}`, providers: ['demo'], source: '矿山安全离线基准', isDemo: true, datasetMode: 'demo', verifiedAt: '2026-09-09T00:00:00Z', relevance: Math.max(.58, .96 - index * .018), novelty: .58 + index % 5 * .07, evidenceGrade: [2, 4, 14, 16].includes(index) ? 'A' : index === 11 ? 'C' : 'B', evidenceProfile: { data: mine.data.length > 0, code: index % 4 === 0, validation: checks.validation }, mine, readiness: { score: readinessScore, level: readinessScore >= 75 ? '可进入工程复核' : readinessScore >= 55 ? '具备试验依据' : '需要补充工程证据', checks }, riskSignal: Math.round((mine.score * .58 + readinessScore * .27 + (.58 + index % 5 * .07) * 15) * 10) / 10 };
}

function createBenchmarkResult(): MineResult {
  const rows: Array<[string, number, string, string[], number, boolean]> = [
    ['露天矿边坡 InSAR 与 GNSS 形变融合', 2026, '演示遥感形变、GNSS 位移和降雨证据融合字段，不代表真实论文。', ['边坡', 'InSAR', 'GNSS', '多源融合'], 12, true],
    ['矿山边坡无人机裂缝识别与现场复核', 2025, '演示 UAV 影像、裂缝分割、量测误差和现场验证。', ['边坡', 'UAV', '机器视觉'], 26, true],
    ['地下矿微震事件检测与岩爆风险研判', 2025, '演示微震波形、震相、事件定位和岩爆风险标签。', ['岩爆', '微震', '事件检测'], 34, false],
    ['矿井瓦斯浓度时序预测与校准', 2024, '演示瓦斯传感、时序模型、提前量与校准误差。', ['瓦斯', '时序预测', '传感器'], 71, true],
    ['矿井突水多场耦合风险识别', 2023, '演示地下水、地质构造与监测信号的物理约束分析。', ['水害', '物理约束', '多源融合'], 83, false],
    ['煤火热红外遥感监测', 2022, '演示热红外异常、地表验证和时间变化分析。', ['火灾', '遥感', '热红外'], 96, true],
    ['矿尘视觉监测与职业暴露评估', 2024, '演示视觉浓度估计、环境传感与暴露评价。', ['粉尘', '机器视觉', '职业健康'], 28, false],
    ['尾矿坝点云变形与数字孪生', 2025, '演示 LiDAR 点云、三维变形和数字孪生更新。', ['尾矿库', '点云', '数字孪生'], 19, true],
    ['冲击地压声发射与微震联合预警', 2021, '演示声发射、微震和物理指标的证据一致性。', ['冲击地压', '声发射', '微震'], 126, false],
    ['矿山安全知识图谱与规程问答', 2025, '演示事故报告、规程文本、知识图谱和引用回答。', ['知识图谱', '安全规程', '大语言模型'], 17, true],
    ['尾矿库溃坝数值模拟与应急推演', 2020, '演示数值模拟、参数敏感性和应急场景。', ['尾矿库', '数值模拟', '应急'], 183, false],
    ['矿山设备人员接近检测', 2023, '演示目标检测、定位误差和现场部署指标。', ['设备安全', '目标检测', '人员定位'], 57, true],
    ['矿山多灾种风险数字孪生', 2026, '演示边坡、瓦斯与水害数据在数字孪生中的统一组织。', ['多灾种', '数字孪生', '多源融合'], 7, true],
    ['边坡位移 Transformer 预测与不确定性', 2024, '演示位移时间序列、预测区间和外部矿区验证。', ['边坡', '时序预测', '不确定性'], 64, false],
    ['矿井通风异常检测与可解释诊断', 2022, '演示通风网络、气体浓度和异常根因。', ['瓦斯', '通风', '异常检测'], 91, true],
    ['矿山灾害多模态基础模型评测', 2026, '演示影像、波形与文本的任务定义、数据隔离和安全评测。', ['多模态', '基础模型', '安全评测'], 3, true],
  ];
  const records = rows.map((row, index) => makeRecord(index + 1, row));
  const workspace: MineWorkspace = { id: 'mine-radar-frontier', name: '矿山安全前沿证据', mode: 'mine', namespace: 'mine-safety', version: 2, query: { main: 'mine safety monitoring AI remote sensing microseismic risk', must: 'monitoring risk', exact: '', exclude: '', startYear: 2020, endYear: 2026, sort: 'relevance', oaOnly: false, providers: ['crossref', 'openalex'], page: 1, perPage: 16, minMineScore: 12 }, collections: [{ id: 'inbox', name: '待筛选' }, { id: 'core', name: '核心安全证据' }, { id: 'methods', name: '监测与算法' }, { id: 'field', name: '工程验证' }], library: [{ recordId: 'mine-01', collectionId: 'core', status: 'included', priority: 'high', tags: ['边坡', '多源融合'], note: '重点核查形变与降雨时间对齐。' }, { recordId: 'mine-02', collectionId: 'field', status: 'included', priority: 'high', tags: ['现场复核', '裂缝'], note: '核验现场样本规模。' }, { recordId: 'mine-03', collectionId: 'core', status: 'included', priority: 'high', tags: ['岩爆', '微震'], note: '检查定位误差与误报。' }, { recordId: 'mine-04', collectionId: 'methods', status: 'maybe', priority: 'medium', tags: ['瓦斯', '预测'], note: '需要独立矿区验证。' }, { recordId: 'mine-08', collectionId: 'field', status: 'included', priority: 'medium', tags: ['尾矿库', '数字孪生'], note: '关注点云更新频率。' }, { recordId: 'mine-14', collectionId: 'methods', status: 'maybe', priority: 'medium', tags: ['不确定性'], note: '需要预测区间覆盖率。' }], evidenceNotes: { use: '矿山相关度只用于初筛，优先复核具备现场、传感、验证和不确定性信息的记录。', limitations: '离线基准不是真实论文；公开元数据也不能替代原文阅读和矿山安全专家判断。' }, monitors: [{ id: 'mine-monitor-weekly', name: '矿山安全 AI 新研究', query: 'mine safety monitoring AI remote sensing microseismic risk', frequency: 'weekly', enabled: true, lastRunAt: '2026-09-09T00:00:00Z', lastStatus: 'succeeded', baselineIds: ['mine-01', 'mine-03', 'mine-04'], newIds: ['mine-01'], delivery: '矿山空间站内记录', nextRunAt: null }], transfer: { selectedIds: ['mine-01', 'mine-02', 'mine-03', 'mine-08'], history: [] }, createdAt: '2026-09-09T00:00:00Z', updatedAt: '2026-09-09T00:00:00Z' };
  const coverage = (group: 'hazards' | 'methods' | 'data', items: readonly (readonly [string, string])[]) => items.map(([id, label]) => ({ id, label, count: records.filter((record) => record.mine[group].some((item) => item.id === id)).length }));
  const hazardCoverage = coverage('hazards', hazards), methodCoverage = coverage('methods', methods), dataCoverage = coverage('data', dataTypes);
  const hazardMethodMatrix = hazardCoverage.flatMap((hazard) => methodCoverage.map((method) => ({ hazardId: hazard.id, methodId: method.id, count: records.filter((record) => record.mine.hazards.some((item) => item.id === hazard.id) && record.mine.methods.some((item) => item.id === method.id)).length })));
  const nodes = [...hazardCoverage.filter((item) => item.count).map((item) => ({ ...item, type: 'hazard', weight: item.count })), ...methodCoverage.filter((item) => item.count).map((item) => ({ ...item, type: 'method', weight: item.count })), ...dataCoverage.filter((item) => item.count).map((item) => ({ ...item, type: 'data', weight: item.count }))];
  const edges = hazardMethodMatrix.filter((item) => item.count).map((item) => ({ id: `${item.hazardId}:${item.methodId}`, source: item.hazardId, target: item.methodId, weight: item.count }));
  const analysis = { yearlyTrend: [2020, 2021, 2022, 2023, 2024, 2025, 2026].map((year) => ({ year, count: records.filter((record) => record.year === year).length })), hazards: hazardCoverage, methods: methodCoverage, data: dataCoverage, hazardMethodMatrix, readinessDistribution: [['低于 40', 0, 40], ['40–54', 40, 55], ['55–74', 55, 75], ['75 以上', 75, 101]].map(([label, low, high]) => ({ label: String(label), count: records.filter((record) => record.readiness.score >= Number(low) && record.readiness.score < Number(high)).length })), graph: { nodes, edges }, riskSignals: records.slice().sort((a, b) => b.riskSignal - a.riskSignal).slice(0, 10).map((record) => ({ recordId: record.id, title: record.title, hazard: record.mine.primaryHazard, method: record.mine.primaryMethod, mineScore: record.mine.score, readiness: record.readiness.score, riskSignal: record.riskSignal, boundary: '筛选信号，不是风险预警' })), duplicateCount: 0, averageMineScore: Math.round(records.reduce((sum, item) => sum + item.mine.score, 0) / records.length * 10) / 10, averageReadiness: Math.round(records.reduce((sum, item) => sum + item.readiness.score, 0) / records.length * 10) / 10, fieldEvidence: records.filter((item) => item.readiness.checks.realWorld).length, reproducibleEvidence: records.filter((item) => item.readiness.checks.reproducibility).length };
  const sources = [{ id: 'crossref', name: 'Crossref', configured: true, enabled: true, status: 'not-checked', rateLimit: '公开 API 限额', lastCheckedAt: null, lastError: '' }, { id: 'openalex', name: 'OpenAlex', configured: true, enabled: true, status: 'not-checked', rateLimit: '公开 API 限额', lastCheckedAt: null, lastError: '' }, { id: 'semantic-scholar', name: 'Semantic Scholar', configured: false, enabled: false, status: 'not-configured', rateLimit: '需要单独配置', lastCheckedAt: null, lastError: '尚未配置' }];
  const bibtex = records.map((item, index) => `@article{Mine${item.year}${index + 1},\n title={${item.title}},\n year={${item.year}},\n doi={${item.doi}}\n}`).join('\n\n'); const ris = records.map((item) => `TY  - JOUR\nTI  - ${item.title}\nPY  - ${item.year}\nDO  - ${item.doi}\nER  - `).join('\n\n'); const transferJson = JSON.stringify({ schema: 'skyview-mine-evidence-transfer', namespace: 'mine-safety', records: records.slice(0, 4) }, null, 2);
  return { schema: 'skyview-mine-safety-radar-results', version: 2, stage: 'run-all', namespace: 'mine-safety', workspace, records, analysis, sources, runtime: { dataSpaceIsolated: true, crossModeReuseRequiresTransfer: true, liveSearchRequiresExplicitAction: true, backgroundSchedulerConfigured: false, persistentNotificationConfigured: false, safetyDecisionAutomation: false }, exports: { bibtex, ris, libraryCsv: `记录ID,标题,灾种,矿山相关度,工程就绪度\n${records.map((item) => `${item.id},${item.title},${item.mine.primaryHazard},${item.mine.score},${item.readiness.score}`).join('\n')}`, alertsMarkdown: '# 矿山安全前沿监测记录\n\n- 矿山安全 AI 新研究：完成', knowledgeMarkdown: '# AI+矿山安全研究雷达资料包\n\n离线基准不是真实论文。', transferJson, backupJson: JSON.stringify({ schema: 'skyview-mine-safety-radar-backup', workspace, records, sources, analysis }, null, 2) } };
}

function Trend({ values }: { values: Array<{ year: number; count: number }> }) {
  const max = Math.max(1, ...values.map((item) => item.count)); const points = values.map((item, index) => `${18 + index * 46},${92 - item.count / max * 61}`).join(' ');
  return <svg className="mine-trend" viewBox="0 0 320 112" aria-label="矿山安全研究年度趋势"><path d="M18 92H302" /><polyline points={points} />{values.map((item, index) => <g key={item.year}><circle cx={18 + index * 46} cy={92 - item.count / max * 61} r="4" /><text x={18 + index * 46} y="108">{String(item.year).slice(2)}</text></g>)}</svg>;
}

export function MineSafetyRadarWorkbench({ executionAllowed = true }: { executionAllowed?: boolean }) {
  const [view, setView] = useState<(typeof views)[number][0]>('overview'); const [result, setResult] = useState<MineResult>(() => createBenchmarkResult());
  const [projects, setProjects] = useState<WorkbenchProject[]>([]); const [projectId, setProjectId] = useState(''); const [projectTitle, setProjectTitle] = useState('矿山安全前沿证据项目');
  const [query, setQuery] = useState(result.workspace.query.main); const [filter, setFilter] = useState(''); const [hazardFilter, setHazardFilter] = useState('all'); const [collectionFilter, setCollectionFilter] = useState('all'); const [selectedId, setSelectedId] = useState(result.records[0].id);
  const [running, setRunning] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const importInput = useRef<HTMLInputElement>(null);
  useEffect(() => { let active = true; toolApi.listProjects('mine-safety-radar').then((items) => { if (!active) return; setProjects(items); const project = items[0]; const saved = project?.state.mineSafetyRadar as { result?: MineResult } | undefined; if (project && saved?.result?.schema === 'skyview-mine-safety-radar-results') { setProjectId(project.id); setProjectTitle(project.title); setResult(saved.result); setQuery(saved.result.workspace.query.main); } }).catch(() => undefined); return () => { active = false; }; }, []);
  const projectState = (next: MineResult = result) => ({ mineSafetyRadar: { namespace: 'mine-safety', result: next } });
  const ensureProject = async () => { const existing = projects.find((item) => item.id === projectId); if (existing) return existing; const created = await toolApi.createProject('mine-safety-radar', projectTitle, projectState()); setProjects((items) => [created, ...items]); setProjectId(created.id); return created; };
  const storeResult = async (project: WorkbenchProject, output: MineResult) => { setResult(output); setQuery(output.workspace.query.main); if (!output.records.some((item) => item.id === selectedId)) setSelectedId(output.records[0]?.id || ''); const saved = await toolApi.updateProject(project.id, projectTitle, projectState(output)); setProjects((items) => [saved, ...items.filter((item) => item.id !== saved.id)]); };
  const execute = async (action: string, extra: Record<string, unknown> = {}) => { if (!executionAllowed) return null; setRunning(true); setError(''); setMessage('Go 已登记矿山空间作业，Python 正在更新分类、工程证据与图表…'); try { const project = await ensureProject(); const created = await toolApi.createJob(project.id, 'mine-safety-radar', action, { state: { workspace: result.workspace, records: result.records, sources: result.sources }, ...extra }, crypto.randomUUID()); const job = await waitForJob(created.job.id); if (!job) throw new Error('作业仍在后台运行。'); if (job.status === 'failed') throw new Error(job.error || '矿山安全雷达计算失败。'); if (job.status === 'canceled') throw new Error('作业已取消。'); const output = job.result as MineResult; if (output.schema !== 'skyview-mine-safety-radar-results' || output.namespace !== 'mine-safety') throw new Error('服务端返回了不兼容或越界的矿山雷达结果。'); await storeResult(project, output); setMessage(action === 'search-live' ? output.liveSearch?.message || '公开来源检索完成。' : '矿山安全雷达已更新。'); return output; } catch (caught) { setError(caught instanceof ApiError || caught instanceof Error ? caught.message : '操作失败。'); setMessage(''); return null; } finally { setRunning(false); } };
  const saveProject = async () => { setSaving(true); try { const existing = projects.find((item) => item.id === projectId); const saved = existing ? await toolApi.updateProject(existing.id, projectTitle, projectState()) : await toolApi.createProject('mine-safety-radar', projectTitle, projectState()); setProjects((items) => [saved, ...items.filter((item) => item.id !== saved.id)]); setProjectId(saved.id); setMessage('矿山安全雷达项目已保存。'); } catch (caught) { setError(caught instanceof Error ? caught.message : '保存失败。'); } finally { setSaving(false); } };
  const createVersion = async () => { try { const project = await ensureProject(); await toolApi.createVersion(project.id, `矿山安全雷达 v${result.workspace.version}`, projectState()); setMessage('已创建矿山空间不可变版本。'); } catch (caught) { setError(caught instanceof Error ? caught.message : '创建版本失败。'); } };
  const selectProject = (id: string) => { setProjectId(id); const project = projects.find((item) => item.id === id); if (!project) { const baseline = createBenchmarkResult(); setResult(baseline); setProjectTitle('矿山安全前沿证据项目'); return; } const saved = project.state.mineSafetyRadar as { result?: MineResult } | undefined; if (saved?.result?.schema === 'skyview-mine-safety-radar-results') { setResult(saved.result); setProjectTitle(project.title); setQuery(saved.result.workspace.query.main); } };
  const importRecords = async (file?: File) => { if (!file) return; if (file.size > 2_000_000) { setError('导入文件不能超过 2 MB。'); return; } await execute('import-records', { fileName: file.name, content: await file.text() }); if (importInput.current) importInput.current.value = ''; };
  const updateWorkspace = (change: (workspace: MineWorkspace) => void) => setResult((current) => { const next = structuredClone(current); change(next.workspace); next.workspace.updatedAt = new Date().toISOString(); return next; });
  const filtered = result.records.filter((item) => (!filter || `${item.title} ${item.abstract} ${item.topics.join(' ')}`.toLowerCase().includes(filter.toLowerCase())) && (hazardFilter === 'all' || item.mine.hazards.some((hazard) => hazard.id === hazardFilter)) && item.mine.score >= result.workspace.query.minMineScore && (!result.workspace.query.oaOnly || item.openAccess));
  const libraryIds = new Set(result.workspace.library.map((item) => item.recordId)); const selected = result.records.find((item) => item.id === selectedId) || result.records[0];
  const library = result.workspace.library.filter((entry) => collectionFilter === 'all' || entry.collectionId === collectionFilter).map((entry) => ({ entry, record: result.records.find((item) => item.id === entry.recordId) })).filter((item) => item.record);
  const graphPositions = useMemo(() => { const positions = new Map<string, { x: number; y: number }>(); const grouped = { hazard: result.analysis.graph.nodes.filter((item) => item.type === 'hazard'), method: result.analysis.graph.nodes.filter((item) => item.type === 'method'), data: result.analysis.graph.nodes.filter((item) => item.type === 'data') }; grouped.hazard.forEach((item, index) => positions.set(item.id, { x: 90, y: 45 + index * 38 })); grouped.method.forEach((item, index) => positions.set(item.id, { x: 300, y: 45 + index * 38 })); grouped.data.forEach((item, index) => positions.set(item.id, { x: 505, y: 60 + index * 45 })); return positions; }, [result.analysis.graph.nodes]);
  const datasetLabel = result.records.some((item) => item.datasetMode === 'live') ? '公开来源实查' : result.records.some((item) => item.datasetMode === 'imported') ? '导入记录' : '矿山离线基准';

  return <div className="mine-workbench">
    <header className="mine-commandbar"><div className="mine-project"><HardHat /><NativeSelect aria-label="选择矿山安全雷达项目" value={projectId} onChange={(event) => selectProject(event.target.value)}><NativeSelectOption value="">当前本地项目</NativeSelectOption>{projects.map((project) => <NativeSelectOption key={project.id} value={project.id}>{project.title}</NativeSelectOption>)}</NativeSelect><Input aria-label="项目名称" value={projectTitle} onChange={(event) => setProjectTitle(event.target.value)} /><span className={datasetLabel === '公开来源实查' ? 'live' : ''}>{datasetLabel}</span><em>独立数据空间</em></div><div className="mine-actions"><input ref={importInput} hidden type="file" accept=".bib,.ris,.json" onChange={(event) => void importRecords(event.target.files?.[0])} /><Button size="sm" variant="outline" onClick={() => importInput.current?.click()}><FileInput />导入文献</Button><Button size="sm" variant="outline" onClick={() => void saveProject()} disabled={saving}>{saving ? <LoaderCircle className="spin" /> : <Save />}保存</Button><Button size="sm" variant="outline" onClick={() => void createVersion()}><Archive />建立版本</Button><Button size="sm" onClick={() => void execute('search-live', { query, providers: result.workspace.query.providers, limit: 16 })} disabled={running}>{running ? <LoaderCircle className="spin" /> : <Search />}公开来源检索</Button></div></header>
    <section className="mine-kpis"><article><Radar /><span>候选研究</span><strong>{result.records.length}</strong><small>{datasetLabel}</small></article><article><ShieldAlert /><span>灾种覆盖</span><strong>{result.analysis.hazards.filter((item) => item.count).length}/8</strong><small>规则命中类别</small></article><article><Gauge /><span>平均工程就绪度</span><strong>{pct(result.analysis.averageReadiness)}</strong><small>{result.analysis.fieldEvidence} 条现场线索</small></article><article><Layers3 /><span>技术方法</span><strong>{result.analysis.methods.filter((item) => item.count).length}/8</strong><small>{result.analysis.data.filter((item) => item.count).length}/6 类数据</small></article><article><ShieldCheck /><span>专业证据库</span><strong>{result.workspace.library.length}</strong><small>{result.workspace.library.filter((item) => item.status === 'included').length} 条纳入</small></article><article><BellRing /><span>前沿监测</span><strong>{result.workspace.monitors.length}</strong><small>当前按需执行</small></article></section>
    <Tabs value={view} onValueChange={(value) => setView(value as typeof view)} className="mine-tabs-shell"><TabsList className="mine-tabs" variant="line">{views.map(([id, label], index) => <TabsTrigger value={id} key={id}><b>{String(index + 1).padStart(2, '0')}</b>{label}</TabsTrigger>)}</TabsList></Tabs>
    {(message || error) && <div className={`mine-status ${error ? 'error' : ''}`}>{error ? <CircleAlert /> : <CheckCircle2 />}<span>{error || message}</span><button aria-label="关闭状态" onClick={() => { setMessage(''); setError(''); }}><X /></button></div>}
    <main className="mine-stage">
      {view === 'overview' && <div className="mine-view mine-overview"><section className="mine-surface mine-hazards"><header><div><span>灾种覆盖</span><strong>8 类矿山安全主题</strong></div><small>词项命中只用于文献初筛</small></header><div>{result.analysis.hazards.map((item) => <button key={item.id} className={item.count ? '' : 'empty'} onClick={() => { setHazardFilter(item.id); setView('discover'); }}><span>{item.id.toUpperCase()}</span><strong>{item.count}</strong><small>{item.label}</small></button>)}</div></section><section className="mine-surface mine-trend-card"><header><span>研究时间信号</span><strong>{result.records.length} 条</strong></header><Trend values={result.analysis.yearlyTrend} /></section><section className="mine-surface mine-readiness"><header><span>工程证据分布</span><strong>{pct(result.analysis.averageReadiness)}</strong></header><div>{result.analysis.readinessDistribution.map((item) => <article key={item.label}><span>{item.label}</span><i><b style={{ width: `${item.count / Math.max(1, ...result.analysis.readinessDistribution.map((entry) => entry.count)) * 100}%` }} /></i><strong>{item.count}</strong></article>)}</div></section><section className="mine-surface mine-signals"><header><div><span>值得复核的研究信号</span><strong>相关度 × 工程线索</strong></div><em>不是风险预警</em></header><div>{result.analysis.riskSignals.slice(0, 6).map((item, index) => <button key={item.recordId} onClick={() => { setSelectedId(item.recordId); setView('evidence'); }}><b>{String(index + 1).padStart(2, '0')}</b><span><strong>{item.title}</strong><small>{item.hazard} · {item.method}</small></span><em>{pct(item.riskSignal)}</em></button>)}</div></section><section className="mine-surface mine-tech"><header><span>方法与数据</span><button onClick={() => setView('graph')}>查看图谱</button></header><div>{result.analysis.methods.filter((item) => item.count).map((item) => <span key={item.id}>{item.label}<b>{item.count}</b></span>)}</div><footer>{result.analysis.data.filter((item) => item.count).map((item) => <span key={item.id}>{item.label} {item.count}</span>)}</footer></section></div>}

      {view === 'discover' && <div className="mine-view mine-discover"><section className="mine-surface mine-query"><div><Search /><Input aria-label="矿山安全检索式" value={query} onChange={(event) => setQuery(event.target.value)} /><Button onClick={() => void execute('search-live', { query, providers: result.workspace.query.providers, limit: 16 })}>运行公开检索</Button></div><footer><span>矿山相关度门槛</span><Input aria-label="矿山相关度门槛" type="number" min="0" max="100" value={result.workspace.query.minMineScore} onChange={(event) => updateWorkspace((workspace) => { workspace.query.minMineScore = Number(event.target.value); })} /><button className={result.workspace.query.oaOnly ? 'active' : ''} onClick={() => updateWorkspace((workspace) => { workspace.query.oaOnly = !workspace.query.oaOnly; })}>只看开放获取</button>{['crossref', 'openalex'].map((provider) => <button className={result.workspace.query.providers.includes(provider) ? 'active' : ''} key={provider} onClick={() => updateWorkspace((workspace) => { workspace.query.providers = workspace.query.providers.includes(provider) ? workspace.query.providers.filter((item) => item !== provider) : [...workspace.query.providers, provider]; })}>{provider === 'crossref' ? 'Crossref' : 'OpenAlex'}</button>)}</footer></section><aside className="mine-surface mine-filter"><header><Filter /><span>专业筛选</span><strong>{filtered.length}</strong></header><Input aria-label="筛选文献" placeholder="题名、摘要或标签" value={filter} onChange={(event) => setFilter(event.target.value)} /><nav><button className={hazardFilter === 'all' ? 'active' : ''} onClick={() => setHazardFilter('all')}>全部灾种</button>{result.analysis.hazards.map((item) => <button className={hazardFilter === item.id ? 'active' : ''} key={item.id} onClick={() => setHazardFilter(item.id)}><span>{item.label}</span><b>{item.count}</b></button>)}</nav><p><ShieldCheck />每条记录显示数据来源与矿山分类；离线基准禁止作为真实论文。</p></aside><section className="mine-results">{filtered.map((item) => <article className={selectedId === item.id ? 'selected' : ''} key={item.id}><header><span>{item.mine.primaryHazard}</span><b>{item.evidenceGrade} 级</b><em>{item.datasetMode === 'demo' ? '矿山离线基准' : item.datasetMode === 'live' ? '公开来源' : '导入记录'}</em></header><h3>{item.title}</h3><small>{item.year} · {item.authors.join('、')} · 引用 {item.citations}</small><p>{item.abstract}</p><div>{item.mine.methods.map((tag) => <span key={tag.id}>{tag.label}</span>)}{item.mine.data.map((tag) => <span key={tag.id}>{tag.label}</span>)}</div><footer><span>矿山相关度 <b>{item.mine.score}</b></span><span>工程就绪度 <b>{item.readiness.score}</b></span><button onClick={() => setSelectedId(item.id)}>查看</button><button onClick={() => void execute('update-library', { recordId: item.id, collectionId: 'inbox', status: 'maybe', priority: 'medium', tags: item.topics, note: '' })}>{libraryIds.has(item.id) ? '已入证据库' : '加入证据库'}</button></footer></article>)}</section></div>}

      {view === 'library' && <div className="mine-view mine-library"><aside className="mine-surface mine-collections"><header><Tags /><span>专业集合</span><strong>{result.workspace.library.length}</strong></header><button className={collectionFilter === 'all' ? 'active' : ''} onClick={() => setCollectionFilter('all')}>全部证据 <b>{result.workspace.library.length}</b></button>{result.workspace.collections.map((item) => <button className={collectionFilter === item.id ? 'active' : ''} key={item.id} onClick={() => setCollectionFilter(item.id)}>{item.name}<b>{result.workspace.library.filter((entry) => entry.collectionId === item.id).length}</b></button>)}<Button variant="outline" onClick={() => void execute('dedupe')}><GitBranch />重新去重</Button><Button variant="outline" onClick={() => downloadText(result.exports.libraryCsv, '矿山安全专业证据库.csv', 'text/csv;charset=utf-8')}><Download />导出证据库</Button></aside><section className="mine-library-list">{library.map(({ entry, record }) => record && <article className={selectedId === record.id ? 'selected' : ''} key={record.id}><header><b>{record.evidenceGrade}</b><strong>{record.title}</strong><em>{record.readiness.score}</em></header><div><span>{record.mine.primaryHazard}</span><span>{record.mine.primaryMethod}</span><span>{entry.status === 'included' ? '已纳入' : '待定'}</span><span>优先级 {entry.priority === 'high' ? '高' : '中'}</span></div><p>{entry.note}</p><footer><button onClick={() => setSelectedId(record.id)}>查看详情</button><button onClick={() => void execute('update-library', { ...entry, recordId: record.id, status: entry.status === 'included' ? 'maybe' : 'included' })}>{entry.status === 'included' ? '改为待定' : '纳入证据'}</button></footer></article>)}</section>{selected && <aside className="mine-surface mine-detail"><header><span>专业证据详情</span><strong>{selected.readiness.level}</strong></header><h3>{selected.title}</h3><p>{selected.abstract}</p><dl><div><dt>灾种</dt><dd>{selected.mine.hazards.map((item) => item.label).join('、') || '未分类'}</dd></div><div><dt>方法</dt><dd>{selected.mine.methods.map((item) => item.label).join('、') || '未识别'}</dd></div><div><dt>数据</dt><dd>{selected.mine.data.map((item) => item.label).join('、') || '未识别'}</dd></div><div><dt>DOI</dt><dd>{selected.doi || '缺失'}</dd></div></dl><a href={selected.url} target="_blank" rel="noreferrer">打开来源 <ExternalLink /></a></aside>}</div>}

      {view === 'graph' && <div className="mine-view mine-graph"><section className="mine-surface mine-network"><header><div><span>灾种—方法—数据图谱</span><strong>{result.analysis.graph.nodes.length} 节点 · {result.analysis.graph.edges.length} 关系</strong></div><small>连线表示当前记录共现</small></header><svg viewBox="0 0 600 360" aria-label="矿山安全灾种技术图谱">{result.analysis.graph.edges.map((edge) => { const source = graphPositions.get(edge.source), target = graphPositions.get(edge.target); return source && target ? <line key={edge.id} x1={source.x} y1={source.y} x2={target.x} y2={target.y} strokeWidth={edge.weight + 1} /> : null; })}{result.analysis.graph.nodes.map((node) => { const point = graphPositions.get(node.id); return point ? <g key={node.id} className={node.type}><circle cx={point.x} cy={point.y} r={7 + Math.min(8, node.weight * 2)} /><text x={point.x + (node.type === 'hazard' ? -16 : 16)} y={point.y + 4}>{node.label.slice(0, 10)}</text></g> : null; })}</svg></section><section className="mine-surface mine-heatmap"><header><span>灾种 × 方法覆盖</span><strong>64 个组合</strong></header><div className="mine-heat-head"><b />{result.analysis.methods.map((method) => <span key={method.id}>{method.label.slice(0, 4)}</span>)}</div>{result.analysis.hazards.map((hazard) => <div className="mine-heat-row" key={hazard.id}><b>{hazard.label}</b>{result.analysis.methods.map((method) => { const count = result.analysis.hazardMethodMatrix.find((item) => item.hazardId === hazard.id && item.methodId === method.id)?.count || 0; return <i key={method.id} className={`level-${Math.min(3, count)}`} title={`${hazard.label} × ${method.label}：${count}`}>{count || '·'}</i>; })}</div>)}</section></div>}

      {view === 'evidence' && <div className="mine-view mine-evidence"><section className="mine-surface mine-readiness-checks"><header><Gauge /><div><span>工程就绪度构成</span><strong>六类透明线索</strong></div><em>不自动作出安全决策</em></header><div>{[['realWorld', '现场或矿区验证'], ['validation', '试验、案例或基准'], ['sensor', '明确传感数据'], ['method', '明确算法方法'], ['reproducibility', '数据集或复现线索'], ['uncertainty', '误差与不确定性']].map(([key, label]) => <article key={key}><span>{label}</span><strong>{result.records.filter((item) => item.readiness.checks[key]).length}</strong><i><b style={{ width: `${result.records.filter((item) => item.readiness.checks[key]).length / result.records.length * 100}%` }} /></i></article>)}</div></section><section className="mine-surface mine-evidence-notes"><header><span>人工用途与局限</span><Button size="sm" onClick={() => void execute('update-evidence', result.workspace.evidenceNotes)}><Save />保存说明</Button></header><label><span>纳入用途</span><textarea value={result.workspace.evidenceNotes.use} onChange={(event) => updateWorkspace((workspace) => { workspace.evidenceNotes.use = event.target.value; })} /></label><label><span>局限和复核</span><textarea value={result.workspace.evidenceNotes.limitations} onChange={(event) => updateWorkspace((workspace) => { workspace.evidenceNotes.limitations = event.target.value; })} /></label></section><section className="mine-surface mine-matrix"><header><span>逐条工程证据矩阵</span><strong>相关度、元数据和工程线索分开呈现</strong></header><div className="mine-matrix-head"><b>等级</b><b>研究记录</b><b>灾种</b><b>矿山相关</b><b>工程就绪</b><b>现场</b><b>验证</b><b>复现</b></div>{result.records.map((item) => <button key={item.id} onClick={() => setSelectedId(item.id)}><b className={`grade-${item.evidenceGrade.toLowerCase()}`}>{item.evidenceGrade}</b><span>{item.title}<small>{item.year} · {item.datasetMode === 'demo' ? '离线基准' : '公开来源'}</small></span><em>{item.mine.primaryHazard}</em><strong>{item.mine.score}</strong><strong>{item.readiness.score}</strong><i className={item.readiness.checks.realWorld ? 'yes' : ''}>{item.readiness.checks.realWorld ? '有' : '无'}</i><i className={item.readiness.checks.validation ? 'yes' : ''}>{item.readiness.checks.validation ? '有' : '无'}</i><i className={item.readiness.checks.reproducibility ? 'yes' : ''}>{item.readiness.checks.reproducibility ? '有' : '无'}</i></button>)}</section></div>}

      {view === 'alerts' && <div className="mine-view mine-alerts"><section className="mine-surface mine-monitor-boundary"><header><BellRing /><div><span>前沿监测边界</span><strong>规则独立保存在矿山空间</strong></div></header><p>当前按需执行；后台定时调度和外部通知尚未配置。每次运行保留基线、新增记录、状态与通知去重键。</p><dl><div><dt>后台调度</dt><dd>未配置</dd></div><div><dt>外部通知</dt><dd>未配置</dd></div><div><dt>站内运行记录</dt><dd>已启用</dd></div></dl></section><section className="mine-monitor-list">{result.workspace.monitors.map((monitor) => <article key={monitor.id}><header><BellRing /><div><strong>{monitor.name}</strong><small>{monitor.query}</small></div><em>每周规则</em></header><div><span>最近运行<b>{monitor.lastRunAt.slice(0, 10)}</b></span><span>基线<b>{monitor.baselineIds.length} 条</b></span><span>新增<b>{monitor.newIds.length} 条</b></span><span>空间<b>矿山安全</b></span></div><footer><span>{monitor.delivery}</span><Button size="sm" onClick={() => void execute('run-monitor', { monitorId: monitor.id })}><Play />立即运行</Button></footer></article>)}</section><section className="mine-surface mine-monitor-runs"><header><span>运行与通知记录</span><Button size="sm" variant="outline" onClick={() => downloadText(result.exports.alertsMarkdown, '矿山安全前沿监测记录.md')}><Download />导出记录</Button></header>{result.workspace.monitorRuns?.length ? result.workspace.monitorRuns.map((run) => <article key={run.id}><CheckCircle2 /><span><strong>运行完成</strong><small>{run.startedAt} · 新增 {run.newIds.length} 条</small></span><em>站内已记录</em></article>) : <p>立即运行后将在这里形成可审计记录。</p>}</section></div>}

      {view === 'transfer' && <div className="mine-view mine-transfer"><section className="mine-surface mine-transfer-summary"><header><Send /><div><span>矿山证据转化</span><strong>{result.workspace.transfer.selectedIds.length} 条已选择</strong></div></header><p>跨工作台复用必须经过显式联动包，并保留 mine-safety 来源空间与目的端人工复核要求。</p><div>{result.workspace.transfer.selectedIds.map((id) => { const item = result.records.find((record) => record.id === id); return item ? <span key={id}>{item.mine.primaryHazard} · {item.title}</span> : null; })}</div></section><section className="mine-transfer-grid">{[['disaster-remote-sensing', '灾害遥感损毁评估', '边坡、尾矿库与热异常影像证据', MapPinned], ['seismic-physics', '地震与物理分析', '微震、声发射与事件检测证据', Waves], ['knowledge-system', '个人知识系统', '规程、摘要和矿山分类资料包', Network], ['patent-transfer', '专利转化', '方法与工程验证线索登记', Sparkles]].map(([id, title, note, Icon]) => <article key={String(id)}><Icon /><span><strong>{String(title)}</strong><small>{String(note)}</small></span><Button size="sm" onClick={() => void execute('transfer', { destination: id, recordIds: result.workspace.transfer.selectedIds })}>生成联动包</Button></article>)}</section><section className="mine-surface mine-delivery"><header><Download /><span>专业交付</span></header><div><button onClick={() => downloadText(result.exports.bibtex, '矿山安全研究文献.bib')}><strong>BibTeX</strong><small>引文管理</small></button><button onClick={() => downloadText(result.exports.ris, '矿山安全研究文献.ris')}><strong>RIS</strong><small>通用交换</small></button><button onClick={() => downloadText(result.exports.libraryCsv, '矿山安全专业证据库.csv', 'text/csv;charset=utf-8')}><strong>证据库 CSV</strong><small>分类与就绪度</small></button><button onClick={() => downloadText(result.exports.knowledgeMarkdown, '矿山安全证据包.md')}><strong>知识资料 MD</strong><small>可读证据包</small></button><button onClick={() => downloadText(result.exports.transferJson, '矿山安全联动包.json', 'application/json;charset=utf-8')}><strong>联动 JSON</strong><small>保留来源空间</small></button><button onClick={() => downloadText(result.exports.backupJson, '矿山安全雷达备份.json', 'application/json;charset=utf-8')}><strong>完整备份</strong><small>项目、证据与分析</small></button></div></section></div>}

      {view === 'sources' && <div className="mine-view mine-sources"><section className="mine-source-grid">{result.sources.map((source) => <article className="mine-surface" key={source.id}><header><Database /><div><span>{source.configured ? '公开文献来源' : '待配置来源'}</span><strong>{source.name}</strong></div><em className={source.status}>{source.status === 'healthy' ? '正常' : source.status === 'failed' ? '异常' : source.status === 'not-configured' ? '未配置' : '待检查'}</em></header><dl><div><dt>启用状态</dt><dd>{source.enabled ? '已启用' : '未启用'}</dd></div><div><dt>最近检查</dt><dd>{source.lastCheckedAt ? source.lastCheckedAt.slice(0, 10) : '尚未实查'}</dd></div><div><dt>返回记录</dt><dd>{source.records ?? '—'}</dd></div><div><dt>响应耗时</dt><dd>{source.latencyMs ? `${source.latencyMs} ms` : '—'}</dd></div></dl><p>{source.lastError || source.rateLimit}</p><Button size="sm" variant="outline" disabled={!source.configured || running} onClick={() => void execute('search-live', { query: 'mine safety', providers: [source.id], limit: 5 })}>检查来源</Button></article>)}</section><section className="mine-surface mine-boundaries"><header><Activity /><div><span>专业运行边界</span><strong>独立、可追溯、需人工复核</strong></div></header><div><article><b>数据空间隔离</b><span>矿山馆藏、监测和笔记不与通用研究雷达混合。</span></article><article><b>透明规则分类</b><span>灾种、方法、数据和就绪度均可查看构成。</span></article><article><b>安全决策边界</b><span>研究信号不自动形成预警、停产或人员安全决策。</span></article><article><b>来源核验</b><span>公开元数据必须回看原文，离线基准禁止冒充真实文献。</span></article></div></section></div>}
    </main>
  </div>;
}
